comment: false

coverage:
  range: 0..90
  round: up
  precision: 0

  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 50%
