comment: false

coverage:
  range: 0..100
  round: up
  precision: 0

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        target: 90             # specify the target coverage for each commit status
                               #   option: "auto" (must increase from parent commit or pull request base)
                               #   option: "X%" a static target percentage to hit
        threshold: null        # allowed to drop X% and still result in a "success" commit status

    patch:
      default:
        enabled: yes           # must be yes|true to enable this status
        target: 0
        threshold: null
