# internal data ----------------------------------------------------------------
devtools::load_all(".") # this loads the gtsummary internal objects as well (to be saved into `df_add_p_tests`)
df_theme_elements <- readr::read_csv("data-raw/gtsummary_theme_elements.csv")
df_translations <- readxl::read_excel("data-raw/gtsummary_translated.xlsx")

special_char <- list()
special_char$interpunct <- "·"

# add_p.* data -----------------------------------------------------------------
# creating a tibble of all possible tests to select from all `add_p.*()` functions
df_add_p_tests <- tibble::tribble(
  ~class,           ~test_package, ~test_name,               ~test_fun,           ~fun_to_run,                                                                           ~accept_dots, ~pseudo_code,                                                                                                                        ~description,
  "tbl_summary",    "stats",       "t.test",                 stats::t.test,       rlang::expr(gtsummary:::add_p_test_t.test),                                            TRUE,         "`t.test(variable ~ as.factor(by), data = data, ...)`",                                                                              "t-test",
  "tbl_summary",    "stats",       "aov",                    stats::aov,          rlang::expr(gtsummary:::add_p_test_aov),                                               FALSE,        "`aov(variable ~ as.factor(by), data = data) %>% summary()`",                                                                        "One-way ANOVA",
  "tbl_summary",    "stats",       "kruskal.test",           stats::kruskal.test, rlang::expr(gtsummary:::add_p_test_kruskal.test),                                      FALSE,        "`kruskal.test(data[[variable]], as.factor(data[[by]]))`",                                                                           "Kruskal-Wallis test",
  "tbl_summary",    "stats",       "wilcox.test",            stats::wilcox.test,  rlang::expr(gtsummary:::add_p_test_wilcox.test),                                       TRUE,         "`wilcox.test(variable ~ as.factor(by), data = data, ...)`",                                                                         "Wilcoxon rank-sum test",
  "tbl_summary",    "stats",       "chisq.test",             stats::chisq.test,   rlang::expr(gtsummary:::add_p_test_chisq.test),                                        TRUE,         "`chisq.test(x = data[[variable]], y = as.factor(data[[by]]), ...)`",                                                                "chi-square test of independence",
  "tbl_summary",    "stats",       "chisq.test.no.correct",  NULL,                rlang::expr(gtsummary:::add_p_test_chisq.test.no.correct),                             FALSE,        "`chisq.test(x = data[[variable]], y = as.factor(data[[by]]), correct = FALSE)`",                                                    "chi-square test of independence",
  "tbl_summary",    "stats",       "fisher.test",            stats::fisher.test,  rlang::expr(gtsummary:::add_p_test_fisher.test),                                       TRUE,         "`fisher.test(data[[variable]], as.factor(data[[by]]), ...)`",                                                                       "Fisher's exact test",
  "tbl_summary",    "lme4",        "lme4",                   lme4::glmer,         rlang::expr(gtsummary:::add_p_test_lme4),                                              FALSE,        "`lme4::glmer(by ~ (1|group), data, family = binomial) %>% anova(lme4::glmer(by ~ variable + (1|group), data, family = binomial))`", "random intercept logistic regression",
  "tbl_svysummary", "survey",      "svy.t.test",             survey::svyttest,    rlang::expr(gtsummary:::add_p_test_svy.t.test),                                        FALSE,        "`survey::svyttest(~variable + by, data)`",                                                                                          "t-test adapted to complex survey samples",
  "tbl_svysummary", "survey",      "svy.wilcox.test",        survey::svyranktest, rlang::expr(gtsummary:::add_p_test_svy.wilcox.test),                                   FALSE,        "`survey::svyranktest(~variable + by, data, test = 'wilcoxon')`",                                                                    "Wilcoxon rank-sum test for complex survey samples",
  "tbl_svysummary", "survey",      "svy.kruskal.test",       NULL,                rlang::expr(gtsummary:::add_p_test_svy.kruskal.test),                                  FALSE,        "`survey::svyranktest(~variable + by, data, test = 'KruskalWallis')`",                                                               "Kruskal-Wallis rank-sum test for complex survey samples",
  "tbl_svysummary", "survey",      "svy.vanderwaerden.test", NULL,                rlang::expr(gtsummary:::add_p_test_svy.vanderwaerden.test),                            FALSE,        "`survey::svyranktest(~variable + by, data, test = 'vanderWaerden')`",                                                               "van der Waerden's normal-scores test for complex survey samples",
  "tbl_svysummary", "survey",      "svy.median.test",        NULL,                rlang::expr(gtsummary:::add_p_test_svy.median.test),                                   FALSE,        "`survey::svyranktest(~variable + by, data, test = 'median')`",                                                                      "Mood's test for the median for complex survey samples",
  "tbl_svysummary", "survey",      "svy.chisq.test",         survey::svychisq,    rlang::expr(gtsummary:::add_p_test_svy.chisq.test),                                    FALSE,        "`survey::svychisq(~variable + by, data, statistic = 'F')`",                                                                         "chi-squared test with Rao & Scott's second-order correction",
  "tbl_svysummary", "survey",      "svy.adj.chisq.test",     NULL,                rlang::expr(gtsummary:::add_p_test_svy.adj.chisq.test),                                FALSE,        "`survey::svychisq(~variable + by, data, statistic = 'Chisq')`",                                                                     "chi-squared test adjusted by a design effect estimate",
  "tbl_svysummary", "survey",      "svy.wald.test",          NULL,                rlang::expr(gtsummary:::add_p_test_svy.wald.test),                                     FALSE,        "`survey::svychisq(~variable + by, data, statistic = 'Wald')`",                                                                      "Wald test of independence for complex survey samples",
  "tbl_svysummary", "survey",      "svy.adj.wald.test",      NULL,                rlang::expr(gtsummary:::add_p_test_svy.adj.wald.test),                                 FALSE,        "`survey::svychisq(~variable + by, data, statistic = 'adjWald')`",                                                                   "adjusted Wald test of independence for complex survey samples",
  "tbl_svysummary", "survey",      "svy.lincom.test",        NULL,                rlang::expr(gtsummary:::add_p_test_svy.lincom.test),                                   FALSE,        "`survey::svychisq(~variable + by, data, statistic = 'lincom')`",                                                                    "test of independence using the exact asymptotic distribution for complex survey samples",
  "tbl_svysummary", "survey",      "svy.saddlepoint.test",   NULL,                rlang::expr(gtsummary:::add_p_test_svy.saddlepoint.test),                              FALSE,        "`survey::svychisq(~variable + by, data, statistic = 'saddlepoint')`",                                                               "test of independence using a saddlepoint approximation for complex survey samples",
  "tbl_survfit",    "survival",    "logrank",                NULL,                rlang::expr(gtsummary:::add_p_tbl_survfit_logrank),                                    FALSE,        "`survival::survdiff(Surv(.) ~ variable, data, rho = 0)`",                                                                           "Log-rank test",
  "tbl_survfit",    "survival",    "petopeto_gehanwilcoxon", NULL,                rlang::expr(gtsummary:::add_p_tbl_survfit_petopeto_gehanwilcoxon),                     FALSE,        "`survival::survdiff(Surv(.) ~ variable, data, rho = 1)`",                                                                           "Peto & Peto modification of Gehan-Wilcoxon test",
  "tbl_survfit",    "survival",    "survdiff",               survival::survdiff,  rlang::expr(gtsummary:::add_p_tbl_survfit_survdiff),                                    TRUE,        "`survival::survdiff(Surv(.) ~ variable, data, ...)`",                                                                               "G-rho family test",
  "tbl_survfit",    "survival",    "coxph_lrt",              survival::coxph,     rlang::expr(purrr::partial(gtsummary:::add_p_tbl_survfit_coxph, test_type = "log")),    TRUE,        "`survival::coxph(Surv(.) ~ variable, data, ...)`",                                                                                  "Cox regression (LRT)",
  "tbl_survfit",    "survival",    "coxph_wald",             NULL,                rlang::expr(purrr::partial(gtsummary:::add_p_tbl_survfit_coxph, test_type = "wald")),   TRUE,        "`survival::coxph(Surv(.) ~ variable, data, ...)`",                                                                                  "Cox regression (Wald)",
  "tbl_survfit",    "survival",    "coxph_score",            NULL,                rlang::expr(purrr::partial(gtsummary:::add_p_tbl_survfit_coxph, test_type = "sc")),     TRUE,        "`survival::coxph(Surv(.) ~ variable, data, ...)`",                                                                                  "Cox regression (Score)"
)




usethis::use_data(df_theme_elements,
                  df_translations,
                  special_char,
                  df_add_p_tests,
                  internal = TRUE, overwrite = TRUE)
