---
title: "Testing font size"
date: "`r format(Sys.Date(), format='%B %d, %Y')`"
output:
  word_document:
    reference_docx: templates/doc_template.docx
  html_document:
    df_print: paged
bibliography: templates/references.bib
csl: templates/european-urology.csl
---

```{r setup, include=FALSE}
# set chunk defaults, code chunks are NOT printed in output for report
knitr::opts_chunk$set(echo = FALSE)
set.seed(20210629)
```

```{r import, include=FALSE}
library(hotverse); library(tidyverse)

# setting MSK ggplot theme, gtsummary theme, and color palette
theme_set(mskRvis::theme_biostat()); mskRvis::set_msk_palette()

```

```{r results, include=FALSE}
tbla <- trial %>%
  select(trt, age, stage, grade) %>%
  tbl_summary(by = trt) %>%
  add_overall()

tblb <- glm(
  response ~ age + stage, trial, family = binomial
  ) %>%
  tbl_regression(exponentiate = TRUE)

tbl1 <- tbla %>%
  # add_p() %>%
  modify_header(label ~ "") %>%
  modify_footnote(everything() ~ NA) 

#tbl_regression example
tblmodel <- tbl_merge(tbls = list(tbla, tblb)) %>%
  modify_header(label ~ "") %>%
  modify_footnote(everything() ~ NA)
  

```

#####
Non-compact

```{r tblmodel1a, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
reset_gtsummary_theme()
tbl1 %>% as_flex_table()
```

```{r tblmodel1b, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
reset_gtsummary_theme()
tblmodel %>% as_flex_table()
```

#####
Default Compact (size 8)

```{r tblmodel2a, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
theme_gtsummary_compact()
tbl1 %>% as_flex_table()
```

```{r tblmodel2b, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
tblmodel %>% as_flex_table()
```

#####

Slightly larger compact (size 10)

```{r tblmodel3a, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
theme_gtsummary_compact(font_size = 10)

tbl1 %>% as_flex_table()
```

```{r tblmodel3b, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
tblmodel %>% as_flex_table()
```

**Obnoxiously larger font size (size 18)
```{r tblmodel4a, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
theme_gtsummary_compact(font_size = 18)

tbl1 %>% as_flex_table()
```

```{r tblmode4b, echo = FALSE, results = "asis", warning = FALSE, message = FALSE}
tblmodel %>% as_flex_table()
```

#####

