# Standalone file: do not edit by hand
# Source: https://github.com/insightsengineering/standalone/blob/HEAD/R/standalone-tibble.R
# Generated by: usethis::use_standalone("insightsengineering/standalone", "tibble")
# ----------------------------------------------------------------------
#
# ---
# repo: insightsengineering/standalone
# file: standalone-tibble.R
# last-updated: 2026-06-30
# license: https://unlicense.org
# imports: [dplyr]
# ---
#
# This file provides a minimal shim to provide a tibble-like API on top of
# base R functions. They are not drop-in replacements but allow a similar style
# of programming.
#
# ## Changelog
# 2026-06-30
#   - `enframe()` now handles `NULL` input and `name = NULL` (value-only output).
#   - `rownames_to_column()` resets to default integer row names, matching
#     `tibble::rownames_to_column()`.
#
# nocov start
# styler: off

deframe <- function(x) {
  if (ncol(x) == 1L) return(x[[1]])
  x[[2]] |> stats::setNames(x[[1]])
}

enframe <- function(x, name = "name", value = "value") {
  if (is.null(x)) x <- logical()

  if (is.null(name)) {
    # value-only tibble; ignore any names on `x`
    lst <- list(unname(x)) |> stats::setNames(value)
  } else if (!is.null(names(x))) {
    lst <- list(names(x), unname(x)) |> stats::setNames(c(name, value))
  } else {
    lst <- list(seq_along(x), unname(x)) |> stats::setNames(c(name, value))
  }
  dplyr::tibble(!!!lst)
}

remove_rownames <- function(.data) {
  rownames(.data) <- NULL
  .data
}

rownames_to_column <- function(.data, var = "rowname") {
  col <- rownames(.data)
  # reset to default integer row names, matching tibble::rownames_to_column()
  rownames(.data) <- NULL
  .data[[var]] <- col

  dplyr::relocate(.data, dplyr::all_of(var), .before = 1L)
}

# nocov end
# styler: on
